# Generated by Django 4.0.6 on 2023-05-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical_ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(default=1, upload_to='idea/'),
            preserve_default=False,
        ),
    ]
